janus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('dartboard/admin/', admin.site.urls),
    path('dartboard/', include('dartboard.urls', namespace="dartboard")),
    path('', RedirectView.as_view(url='/personal_homepage/', permanent=False)),
    path('personal_homepage/', include('personal_homepage.urls', namespace="personal_homepage")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('health/', include('health_check.urls')),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

personal_homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from . import views

app_name="personal_homepage"
urlpatterns = [
    path('', views.personal_index, name='index'),
    path('projects/power-distribution-module/', views.power_distribution_module, name='power-distribution-module'),
    path('projects/ride-height-sensor/', views.ride_height_sensor, name='ride-height-sensor'),
    path('projects/strain-gauge-amp/', views.strain_gauge_amp, name='strain-gauge-amp'),
    path('projects/slip-angle-sensor/', views.slip_angle_sensor, name='slip-angle-sensor'),
    path('projects/khab-2018/', views.khab_2018, name='khab-2018'),
]

personal_homepage/models.py
from django.db import models

# Create your models here.

personal_homepage/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import DeleteView, CreateView
import json
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
def personal_index(request):
    return render(request, 'personal_index.html')

def power_distribution_module(request):
    return render(request, 'power_distribution_module.html')

def ride_height_sensor(request):
    return render(request, 'ride_height_sensor.html')

def strain_gauge_amp(request):
    return render(request, 'strain_gauge_amp.html')

def slip_angle_sensor(request):
    return render(request, 'slip_angle_sensor.html')

def khab_2018(request):
    return render(request, 'khab_2018.html')

personal_homepage/templates/khab_2018.html
{% extends "personal_base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="page-header header">
      <h1>
        Khab 2018
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <p style="text-align:center">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
  </div>
</div>
{% endblock %}

personal_homepage/templates/personal_base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Henry O'Callaghan</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="icon" href="{% static 'favicon.ico' %}" />
  <link rel="stylesheet" href="{% static 'css/personal-styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>

{% block content %}

{% endblock %}

<body class="background">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

personal_homepage/templates/personal_index.html
{% extends "personal_base_generic.html" %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-2">
			<img alt="The man, the myth" src="/static/images/index.png" class="home-image"/>
		</div>
		<div class="col-md-10">
			<div class="jumbotron">
				<h2>
					Hello, I'm Henry
				</h2>
				<p>
					I'm a Computer Engineering student at the U of MN.<br>
					I like to make stuff. Below are some of the things I've helped make.
				</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4" style=text-align:center>
			<h2>
				Formula SAE
			</h2>
			<button class="btn btn-block alt-button" onclick="window.location.href='{% url 'personal_homepage:power-distribution-module' %}'">Power Distribution Module</button>
			<button class="btn btn-block alt-button" onclick="window.location.href='{% url 'personal_homepage:ride-height-sensor' %}'">Ride Height Sensor</button>
			<button class="btn btn-block alt-button" onclick="window.location.href='{% url 'personal_homepage:strain-gauge-amp' %}'">Strain Gauge Amp</button>
			<button class="btn btn-block alt-button" onclick="window.location.href='{% url 'personal_homepage:slip-angle-sensor' %}'">Slip Angle Sensor</button>
		</div>
		<div class="col-md-4" style=text-align:center>
			<h2>
				KHAB Systems
			</h2>
			<button class="btn btn-block alt-button" onclick="window.location.href='{% url 'personal_homepage:khab-2018' %}'">Summer 2018 Work</button>
		</div>
		<div class="col-md-4" style=text-align:center>
			<h2>
				This Site
			</h2>
			<button class="btn btn-block alt-button" style="margin-bottom:15px" onclick="window.location.href='{% url 'dartboard:index' %}'">Janus</button>
		</div>
	</div>
</div>
{% endblock %}

personal_homepage/templates/power_distribution_module.html
{% extends "personal_base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="page-header header">
      <h1>
        Power Distribution Module
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <p style="text-align:center">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
  </div>
</div>
{% endblock %}

personal_homepage/templates/ride_height_sensor.html
{% extends "personal_base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="page-header header">
      <h1>
        Ride Height Sensor
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <p style="text-align:center">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
  </div>
</div>
{% endblock %}

personal_homepage/templates/slip_angle_sensor.html
{% extends "personal_base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="page-header header">
      <h1>
        Slip Angle Sensor
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <p style="text-align:center">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
  </div>
</div>
{% endblock %}

personal_homepage/templates/strain_gauge_amp.html
{% extends "personal_base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="page-header header">
      <h1>
        Strain Gauge Amp
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <p style="text-align:center">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
  </div>
</div>
{% endblock %}