dartboard/urls.py
from django.urls import path
from . import views

app_name="dartboard"
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('choose', views.choose, name='choose'),
    path('choices', views.view_choices, name='choices'),
    path('choices/add/', views.add_choices_user, name='add-choices-user'),
    path('signup', views.SignUp.as_view(), name='signup'),
]

janus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('dartboard/admin/', admin.site.urls),
    path('dartboard/', include('dartboard.urls', namespace="dartboard")),
    path('', RedirectView.as_view(url='/personal_homepage/', permanent=False)),
    path('personal_homepage/', include('personal_homepage.urls', namespace="personal_homepage")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('health/', include('health_check.urls')),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dartboard/models.py
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.db import models
from django.contrib.auth.models import User
import datetime
import time

# Create your models here.

class Choice(models.Model):
    """Model representing a choice for a decsion."""
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    decision = models.ForeignKey('Decision', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, help_text='Enter the name of the choice')

    def __str__(self):
        """String for representing the Model object."""
        return self.name
    """
    def get_absolute_url(self):
        #Returns the url to access a detail record for this book.
        return reverse('choice-detail-view', args=[str(self.id)])
    """

class Decision(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(max_length=200, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return "lol"

dartboard/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class AddChoicesForm(forms.Form):
    c1 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 1'}), required=True)
    c2 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 2'}), required=False)
    c3 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 3'}), required=False)
    c4 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 4'}), required=False)
    c5 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 5'}), required=False)
    c6 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 6'}), required=False)
    c7 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 7'}), required=False)
    c8 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 8'}), required=False)
    c9 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 9'}), required=False)
    c10 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Choice 10'}), required=False)

    def clean_c1 (self):
        data = self.cleaned_data['c1']
        return data

    def clean_c2 (self):
        data = self.cleaned_data['c2']
        return data

    def clean_c3 (self):
        data = self.cleaned_data['c3']
        return data

    def clean_c4 (self):
        data = self.cleaned_data['c4']
        return data

    def clean_c5 (self):
        data = self.cleaned_data['c5']
        return data

    def clean_c6 (self):
        data = self.cleaned_data['c6']
        return data

    def clean_c7 (self):
        data = self.cleaned_data['c7']
        return data

    def clean_c8 (self):
        data = self.cleaned_data['c8']
        return data

    def clean_c9 (self):
        data = self.cleaned_data['c9']
        return data

    def clean_c10 (self):
        data = self.cleaned_data['c10']
        return data

dartboard/views.py
from dartboard.models import Choice, Decision
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from dartboard.forms import AddChoicesForm
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import DeleteView, CreateView
import json
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from datetime import datetime, timedelta
# Create your views here.

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_choices = -1
    num_visits = request.session.get('num_visits', 0)
    if request.user.is_authenticated:
        num_choices = len(Decision.objects.filter(author=request.user))
    else:
        num_choices = len(Decision.objects.filter())
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_choices': num_choices,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def about(request):
    """View function for about page of site"""
    return render(request, 'about.html')

def view_choices(request):
    #Generic class-based view listing books on loan to current user.
    template_name ='choice_list_author.html'
    context = {'choice_list' : Choice.objects.filter(author=request.user).order_by('decision', 'name')}
    return render(request, 'choice_list_author.html', context=context)

def add_choices_user(request):

    #time_threshold = datetime.now() - timedelta(hours=5)
    #Deletes old choices
    #Choice.objects.filter(author=request.user, timestamp).delete()
    decision = Decision()
    choices = [Choice(), Choice(), Choice(), Choice(), Choice(), Choice(), Choice(), Choice(), Choice(), Choice()]
    if request.user.is_authenticated:
        decision.author = request.user

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = AddChoicesForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            choices[0].name = form.cleaned_data['c1']
            choices[1].name = form.cleaned_data['c2']
            choices[2].name = form.cleaned_data['c3']
            choices[3].name = form.cleaned_data['c4']
            choices[4].name = form.cleaned_data['c5']
            choices[5].name = form.cleaned_data['c6']
            choices[6].name = form.cleaned_data['c7']
            choices[7].name = form.cleaned_data['c8']
            choices[8].name = form.cleaned_data['c9']
            choices[9].name = form.cleaned_data['c10']

            currentTime = datetime.now()
            if request.user.is_authenticated:
                decision.timestamp = currentTime
                decision.save()
                for choice in choices:
                    if choice.name is not '':
                        choice.author = request.user
                        choice.decision = decision
                        choice.save()
            else:
                anonChoices = []
                for choice in choices:
                    if choice.name is not '':
                        anonChoices.append(choice.name)
                request.session.get('choices', 0)
                request.session['choices'] = anonChoices
                request.session.modified = True

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('dartboard:choose')) #should redirect to enter choices page

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_name = 'What to eat for dinner'
        form = AddChoicesForm()

    context = {
        'decision' : decision,
        'form': form,
        'c1': choices[0],
        'c2': choices[1],
        'c3': choices[2],
        'c4': choices[3],
        'c5': choices[4],
        'c6': choices[5],
        'c7': choices[6],
        'c8': choices[7],
        'c9': choices[8],
        'c10': choices[9],
    }

    return render(request, 'add_choices_user.html', context)

def choose(request):
    if request.user.is_authenticated:
        currentDecision = Decision.objects.filter(author=request.user).order_by('-timestamp')[0]
        choices = Choice.objects.filter(decision=currentDecision)
    else:
        choices = request.session.get('choices')

    context = {
        'choices': choices,
    }

    return render(request, 'choose.html', context=context)

dartboard/templates/about.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="page-header header">
      <h1>
        Janus: The Decision Making Dartboard
      </h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <p style="text-align:center">Janus is a project built on Elastic Beanstalk using Django to help remove whatever semblance of agency you think have in your life. It's meant to help make decisions for you when you're tired, don't care, or just want to simplify your decision making process.</p>
  </div>
</div>
{% endblock %}

dartboard/templates/add_choices_user.html
{% extends "base_generic.html" %}
{% load staticfiles %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="header">
			<h1>
				Add your Choices
			</h1>
		</div>
	</div>
</div>
<form action="" method="post">
  <div class="row" id="1">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-text">
      {% csrf_token %}
      {{ form.c1.help_text }} {{ form.c1 }}
    </div>
  </div>
  <div class="row" id="2">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c2.help_text }} {{ form.c2 }}
    </div>
  </div>
  <div class="row" id="3">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c3.help_text }} {{ form.c3 }}
    </div>
  </div>
  <div class="row" id="4">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c4.help_text }} {{ form.c4 }}
    </div>
  </div>
  <div class="row" id="5">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c5.help_text }} {{ form.c5 }}
    </div>
  </div>
  <div class="row" id="6">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c6.help_text }} {{ form.c6 }}
    </div>
  </div>
  <div class="row" id="7">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c7.help_text }} {{ form.c7 }}
    </div>
  </div>
  <div class="row" id="8">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c8.help_text }} {{ form.c8 }}
    </div>
  </div>
  <div class="row" id="9">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c9.help_text }} {{ form.c9 }}
    </div>
  </div>
  <div class="row" id="10">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      {{ form.c10.help_text }} {{ form.c10 }}
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 choice-input">
      <button onclick="showNext()" id="11" type="button" class="btn btn-block alt-button">Add Choice</button>
      <input type="submit" value="Submit" class="btn btn-block default-button" style="margin-bottom: 10px;">
			{% if not user.is_authenticated %}
			<button class="btn btn-block alt-button" onclick="window.location.href='{% url 'login'%}'">Login to save your choices!</button>
			{% endif %}
    </div>
  </div>
</form>

<script src="{% static '/js/input.js' %}"></script>

{% endblock %}

dartboard/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Janus</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="icon" href="{% static 'favicon.ico' %}" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.8.10/themes/smoothness/jquery-ui.css" type="text/css">
  <script type="text/javascript" src="//ajax.aspnetcdn.com/ajax/jquery.ui/1.8.10/jquery-ui.min.js"></script>

</head>

<body class="background">
  <div class="container-fluid">
    <div class="row">
      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'dartboard:index' %}">Home</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
        <a href="{% url 'dartboard:choices' %}">My Choices</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}
        <a href="{% url 'dartboard:about' %}">About</a>
      </div>
      <span class="sidebar-button" onclick="openNav()">&#9776; Menu</span>

      <script src="{% static '/js/menu-pane.js' %}"></script>

      <div class="col-sm-12 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

dartboard/templates/choice_list_author.html
{% extends "base_generic.html" %}

{% block content %}
{% if choice_list %}
{% regroup choice_list by decision.timestamp as choices %}
<div class="row">
	<div class="col-md-12">
		<h1 style="text-align:center">Choices</h1>
		{% for decision in choices %}
		{{ decision.grouper }}
		<ul class="choice-list">
			{% for choice in decision.list %}
			<li>{{ choice.name }}</li>
			{% endfor %}
		</ul>
		{% endfor %}
	</div>
</div>
{% else %}
<div class="row">
	<div class="col-md-1">
	</div>
	<div class="col-md-10">
		<p style="text-align:center">You have entered no choices.</p>
	</div>
</div>
{% endif %}
{% endblock %}

dartboard/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="header">
			<h1>
				Janus: The Decision Making Dartboard
			</h1>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-md-8">
		<form action="{% url 'dartboard:add-choices-user' %}">
			<button type="submit" class="btn btn-block default-button">
				Start!
			</button>
		</form>
	</div>
</div>
<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-md-8">
		<p class="view-count">Hello {% if user.is_authenticated %}{{ user.get_username }}! You've made {{ num_choices }}{% else %}stranger! Users have made {{ num_choices }}{% endif %}{% if num_choices == 1 %} choice{% else %} choices{% endif %} with Janus.</p>
	</div>
</div>
{% endblock %}

dartboard/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base_generic.html' %}
{% block content %}
<form method="post" class="login-table">
  <div class="row">
    <div class="col-md-12">
      <h2 class="signup-header">Sign up</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-12" style="margin-top: 5px;">
          {{ form.username.label_tag }}
          <div class="row">
            <div class="col-md-12" style="margin-top: 5px; margin-bottom: 5px;">
              {{ form.username }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {{ form.password1.label_tag }}
          <div class="row">
            <div class="col-md-12" style="margin-top: 5px; margin-bottom: 5px;">
              {{ form.password1 }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {{ form.password2.label_tag }}
          <div class="row">
            <div class="col-md-12" style="margin-top: 5px; margin-bottom: 5px;">
              {{ form.password2 }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 offset-md-4">
      {% if form.errors %}
      {% for field in form %}
      {% for error in field.errors %}
      <p style="text-align:center; margin-top:10px;">{{ error }}</p>
      {% endfor %}
      {% endfor %}
      {% endif %}
      <input type="submit" value="Submit" class="btn btn-block login-button default-button">
    </div>
  </div>
</form>
{% endblock %}